name: Terraform Apply

on:

  workflow_dispatch:
    inputs:
      terraform_version:
        description: Terraform version to create the infra
        type: string
        required: false
        default: '1.5.1'
      apply:
        description: Apply
        type: boolean
        required: false
        default: true


jobs:
  terraform:
    uses: tf-init-nxp/terraform-reusable-workflow/.github/workflows/terraform-apply.yml@main
    with:
      terraform_version: ${{ inputs.terraform_version }}
      apply: ${{ inputs.apply }}
    secrets: inherit
